esphome:
  name: garage-door
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password 
  domain: !secret domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Relay"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret garage_api_key

ota:
  password: !secret ota_password

# Enable Web server
web_server:
  port: 80

#Garage Door

binary_sensor:
- platform: gpio
  pin:
    number: GPIO12
    mode: INPUT_PULLUP
    inverted: False
  name: "Garage Door Sensor"
  id: garage_door_sensor
  device_class: garage_door
  filters:
    - delayed_on: 500ms
    - delayed_off: 500ms
    - delayed_on_off: 1s

switch:
- platform: gpio
  id: relay1
  pin:
    number: GPIO21
    inverted: False
  restore_mode: ALWAYS_OFF
- platform: template
  name: "Garage Door Switch"
  icon: "mdi:garage"
  turn_on_action:
  - switch.turn_on: relay1
  - delay: 1s
  - switch.turn_off: relay1

cover:
  - platform: template
    name: Garage Door
    device_class: garage
    lambda: !lambda |-
      if (id(garage_door_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay1
      - delay: 1s
      - switch.turn_off: relay1
    close_action:
      - switch.turn_on: relay1
      - delay: 1s
      - switch.turn_off: relay1
    stop_action:
      - switch.turn_on: relay1
      - delay: 1s
      - switch.turn_off: relay1

#Temperature Sensor

sensor:
  - platform: dallas
    address: 0x8B01192D506AD828
    name: "Garage Temperature"

dallas:
  - pin: 14