#################################################################
## Bedtime Automations
#################################################################

        ##########################################################
        ## Bedtime Locks
        ##########################################################

- alias: Bedtime - Locks
  id: 'bedtime_locks'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: lock.lock
      target:
        entity_id:
          - lock.front_door
          - lock.back_door
          - lock.basement_door

        ##########################################################
        ## Bedtime Media
        ##########################################################

- alias: Bedtime - Media
  id: 'bedtime_media'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 30

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: select.select_option
      data:
        entity_id: select.living_room_tv_activities
        option: "power_off"
    - action: select.select_option
      data:
        entity_id: select.USER1_s_office_tv_activities
        option: "power_off"
    - action: input_select.select_option
      data:
        entity_id: input_select.sonos
        option: "None"
    - action: media_player.media_stop
      target:
        entity_id:
          - media_player.sonos_surround_sound
          - media_player.sonos_living_room
          - media_player.sonos_dining_room
          - media_player.sonos_kitchen
          - media_player.sonos_bathroom
          - media_player.sonos_bedroom
          - media_player.sonos_bedroom_closet
          - media_player.sonos_USER1s_office
          - media_player.sonos_USER2s_office
          - media_player.sonos_move
          - media_player.sonos_craft_room
          - media_player.sonos_fitness_room
          - media_player.sonos_backyard_patio
          - media_player.sonos_roam

        ##########################################################
        ## Bedtime Blinds
        ##########################################################

- alias: Bedtime - Blinds
  id: 'bedtime_blinds'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
      - condition: state
        entity_id: cover.kitchen_blinds
        state: 'open'
      - condition: state
        entity_id: cover.bedroom_closet_blinds
        state: 'open'
      - condition: state
        entity_id: cover.stairs_blinds
        state: 'open'

  actions:
    - action: cover.close_cover
      target:
        entity_id:
          - cover.stairs_blinds
    - action: cover.close_cover
      target:
        entity_id:
          - cover.bedroom_closet_blinds
    - action: cover.close_cover
      target:
        entity_id:
          - cover.kitchen_blinds

        ##########################################################
        ## Bedtime Helpers
        ##########################################################

- alias: Bedtime - Helpers
  id: 'bedtime_helpers'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: homeassistant.turn_off
      target:
        entity_id:
          - input_boolean.office_rainbow
          - input_boolean.livingroom_rainbow
          - input_boolean.bedroom_rainbow
          - input_boolean.front_porch_rainbow
          - input_boolean.pop_music
          - input_boolean.jazz_music
          - input_boolean.chill_music
          - input_boolean.electronic_music
          - input_boolean.classical_music
          - input_boolean.group_all_sonos
          - input_boolean.view_package_camera
          - input_boolean.package_camera_notification

        ##########################################################
        ## Bedtime Fans
        ##########################################################

- alias: Bedtime - Fans
  id: 'bedtime_fans'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 3
        seconds: 30

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: fan.turn_off
      target:
        entity_id:
          - fan.USER1s_office_fan
          - fan.living_room_east
          - fan.living_room_west

        ##########################################################
        ## Bedtime Switches
        ##########################################################

- alias: Bedtime - Switches
  id: 'bedtime_switches'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: switch.turn_off
      target:
        entity_id:
          - switch.USER1s_office_air_purifier
          - switch.lower_backyard_lighting
          - switch.backyard_patio_lighting
          - switch.fireplace
          - switch.fountain
          - switch.fountain_lights

        ##########################################################
        ## Bedtime Lights
        ##########################################################

- alias: Bedtime - Lights
  id: 'bedtime_lights'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.interior_lights
      state: 'on'
    - condition: state
      entity_id: input_boolean.overnight_guest_mode
      state: 'off'

  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.interior_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_patio
    - delay: '00:00:60'
    - action: light.turn_off
      target:
        entity_id:
          - light.interior_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_patio

        ##########################################################
        ## Bedtime Guest Mode
        ##########################################################

- alias: Bedtime - Guest Mode
  id: 'bedtime_guest_mode'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.overnight_guest_mode
      state: 'on'

  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.living_room_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.dining_room_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.bedroom_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.USER2s_bedroom_closet
    - action: light.turn_off
      target:
        entity_id:
          - light.kitchen_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.hallway_light
    - action: light.turn_off
      target:
        entity_id:
          - light.bathroom_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.basement_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.basement_stairs
    - action: light.turn_off
      target:
        entity_id:
          - light.work_bench_light
    - action: light.turn_off
      target:
        entity_id:
          - light.laundry_room_light
    - action: light.turn_off
      target:
        entity_id:
          - light.basement_stairs
    - action: light.turn_off
      target:
        entity_id:
          - light.craft_room_ceiling
    - action: light.turn_off
      target:
        entity_id:
          - light.fitness_room_ceiling
    - action: light.turn_off
      target:
        entity_id:
          - light.basement_lamp
    - action: light.turn_off
      target:
        entity_id:
          - light.USER1_office_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.USER2_office_lights
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_patio
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: 'Guest'
    - action: light.turn_off
      target:
        entity_id:
          - light.USER1s_office_desktop_clock
          - light.living_room_clock

        ##########################################################
        ## Bedtime Thermostat
        ##########################################################

- alias: Bedtime - Thermostat
  id: 'bedtime_thermostat'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.overnight_guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '23:00:00'

  actions:
    - action: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: 'sleep'

        ##########################################################
        ## Bedtime Exterior Lights
        ##########################################################

- alias: Bedtime - Exterior Lights
  id: 'bedtime_exterior_lights'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 30

  conditions:
    - condition: time
      after: '00:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.front_porch
    - action: light.turn_off
      target:
        entity_id:
          - light.back_door
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_light
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_patio
    - delay: '00:00:60'
    - action: light.turn_off
      target:
        entity_id:
          - light.front_porch
    - action: light.turn_off
      target:
        entity_id:
          - light.back_door
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_light
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_patio
    - action: switch.turn_off
      target:
        entity_id:
          - switch.lower_backyard_lighting
          - switch.backyard_patio_lighting
          - switch.fountain
          - switch.fountain_lights

        ##########################################################
        ## Bedtime Exterior Lights Holiday
        ##########################################################

- alias: Bedtime - Bedtime Exterior Lights Holiday
  id: 'bedtime_exterior_lights_holiday'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 30

  conditions:
    - condition: time
      after: '00:00:00'
      before: '07:30:00'
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.holiday
          state: 'None'

  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.back_door
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_light
    - action: light.turn_off
      target:
        entity_id:
           light.backyard_patio
    - action: light.turn_off
      target:
        entity_id:
           light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: switch.turn_off
      target:
        entity_id:
          - switch.lower_backyard_lighting
          - switch.backyard_patio_lighting
    - delay: '00:00:30'
    - action: light.turn_off
      target:
        entity_id:
          - light.back_door
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_light
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_deck
    - action: light.turn_off
      target:
        entity_id:
          - light.garage_interior
    - action: light.turn_off
      target:
        entity_id:
          - light.backyard_patio

        ##########################################################
        ## Bedtime Garage Door
        ##########################################################

- alias: Bedtime - Garage Door
  id: 'bedtime_garage_door'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 30

  conditions:
    - condition: state
      entity_id: cover.garage_door
      state: 'open'
    - condition: state
      entity_id: input_boolean.garage_door_motor
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.garage_interior
      data:
       flash: long
    - delay: '00:00:15'
    - action: cover.close_cover
      entity_id: cover.garage_door

        ##########################################################
        ## Bedtime - USER1's Office Blinds
        ##########################################################

- alias: Bedtime USER1's Office Blinds
  id: 'bedtime_USER1_office_blinds'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 30

  conditions:
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'

  actions:
    - action: cover.close_cover
      target:
        entity_id:
          - cover.USER1_s_office_blinds

        ##########################################################
        ## Bedtime - USER1's Office Blinds Portable AC
        ##########################################################

- alias: Bedtime USER1's Office Blinds Portable AC
  id: 'bedtime_USER1_office_blinds_portable_ac'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 30

  conditions:
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_office_portable_ac
      state: 'on'

  actions:
    - action: cover.close_cover
      target:
        entity_id:  
          - cover.USER1s_office_blinds_left
          - cover.USER1s_office_blinds_center
    - action: cover.set_cover_position
      data:
        entity_id: 
          - cover.USER1s_office_blinds_right
        position: 13

        ##########################################################
        ## Bedtime - USER2's Office Blinds
        ##########################################################

- alias: Bedtime USER2's Office Blinds
  id: 'bedtime_USER2_office_blinds'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 30

  conditions:
    - condition: state
      entity_id: input_boolean.USER2_office_portable_ac
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'

  actions:
    - action: cover.close_cover
      target:
        entity_id:
          - cover.USER2_s_office_blinds

        ##########################################################
        ## Bedtime - USER2's Office Blinds Portable AC
        ##########################################################

- alias: Bedtime USER2's Office Blinds Portable AC
  id: 'bedtime_USER2_office_blinds_portable_ac'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 30

  conditions:
    - condition: state
      entity_id: input_boolean.USER2_office_portable_ac
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'

  actions:
    - action: cover.close_cover
      target:
        entity_id: 
          - cover.USER2s_office_blinds_left
    - action: cover.set_cover_position
      data:
        entity_id: 
          - cover.USER2s_office_blinds_right
        position: 15

        ##########################################################
        ## Reset Bedtime Switch
        ##########################################################

- alias: Bedtime - Reset Switch
  id: 'bedtime_reset_switch'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  actions:
    - action: homeassistant.turn_off
      entity_id: input_boolean.bedtime
