#################################################################
## Energy
#################################################################

        ##########################################################
        ## Set Winter Rate First 750
        ##########################################################

- alias: Energy - Set Winter Rate First 750
  id: 'energy_set_winter_rate_first_750'

  trigger:
    - trigger: state
      entity_id: 
          - sensor.monthly_electric

  conditions:
    - condition: template
      value_template: "{{ now().month in [1,2,3,4,5,10,11,12] }}"
    - condition: template
      value_template: '{{ trigger.to_state.state | float(0) < 750000 }}'
    - condition: not
      conditions:
      - condition: state
        entity_id: select.monthly_electric
        state: "Winter Rate First 750"

  actions:
    - action: select.select_option
      data:
        entity_id: select.monthly_electric
        option: "Winter Rate First 750"

        ##########################################################
        ## Set Winter Rate Over 750
        ##########################################################

- alias: Energy - Set Winter Rate Over 750
  id: 'energy_set_winter_rate_over_750'

  trigger:
    - trigger: state
      entity_id: 
          - sensor.monthly_electric

  conditions:
    - condition: template
      value_template: "{{ now().month in [1,2,3,4,5,10,11,12] }}"
    - condition: template
      value_template: '{{ trigger.to_state.state | float(0) > 749999 }}'
    - condition: not
      conditions:
      - condition: state
        entity_id: select.monthly_electric
        state: "Winter Rate Over 750"

  actions:
    - action: select.select_option
      data:
        entity_id: select.monthly_electric
        option: "Winter Rate Over 750"

        ##########################################################
        ## Set Summer Rate
        ##########################################################

- alias: Energy - Set Summer Rate
  id: 'energy_set_summer_rate'

  trigger:
    - trigger: state
      entity_id: 
          - sensor.monthly_electric

  conditions:
    - condition: template
      value_template: "{{ now().month in [6,7,8,9] }}"
    - condition: not
      conditions:
      - condition: state
        entity_id: select.monthly_electric
        state: "Summer Rate"

  actions:
    - action: select.select_option
      data:
        entity_id: select.monthly_electric
        option: "Summer Rate"

        ##########################################################
        ## Turn Off USER1 Electric Bike Chargers when Not Charging
        ##########################################################

- alias: Energy - Turn Off USER1 Electric Bike Chargers when Not Charging
  id: 'energy_turn_off_USER1_ebike_chargers_when_not_charging'

  trigger:
    - trigger: numeric_state
      entity_id: sensor.USER1s_bike_charger_current_consumption
      below: 1
      for:
        hours: 0
        minutes: 30
        seconds: 0

  conditions:
    - condition: state
      entity_id: switch.USER1s_bike_charger
      state: 'on'

  actions:
    - action: switch.turn_off
      data:
        entity_id: switch.USER1s_bike_charger

        ##########################################################
        ## Turn Off USER2 Electric Bike Chargers when Not Charging
        ##########################################################

- alias: Energy - Turn Off USER2 Electric Bike Chargers when Not Charging
  id: 'energy_turn_off_USER2_ebike_chargers_when_not_charging'

  trigger:
    - trigger: numeric_state
      entity_id: sensor.USER2s_bike_charger_current_consumption
      below: 1
      for:
        hours: 0
        minutes: 30
        seconds: 0

  conditions:
    - condition: state
      entity_id: switch.USER2s_bike_charger
      state: 'on'

  actions:
    - action: switch.turn_off
      data:
        entity_id: switch.USER2s_bike_charger