#################################################################
## Laundry Automations
#################################################################

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Washing Machine Done - USER1 iOS Notification
        ##########################################################

- alias: Laundry - Washing Machine Done USER1 iOS Notification
  id: 'laundry_washing_machine_done_USER1_ios_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Washing Machine Finished
        data:
          tag: washer

        ##########################################################
        ## Dryer Done - USER1 iOS Notification
        ##########################################################

- alias: Laundry - Dryer Done USER1 iOS Notification
  id: 'laundry_dryer_done_USER1_ios_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.dryer_dry_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Dryer Finished
        data:
          tag: dryer

        ##########################################################
        ## Washing Machine Done - USER2 iOS Notification
        ##########################################################

- alias: Laundry - Washing Machine Done USER2 iOS Notification
  id: 'laundry_washing_machine_done_USER2_ios_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER2_devices
      data:
        message: Washing Machine Finished
        data:
          tag: washer

        ##########################################################
        ## Dryer Done - USER2 iOS Notification
        ##########################################################

- alias: Laundry - Dryer Done USER2 iOS Notification
  id: 'laundry_dryer_done_USER2_ios_notficiation'

  triggers:
    - trigger: state
      entity_id: binary_sensor.dryer_dry_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER2_devices
      data:
        message: Dryer Finished
        data:
          tag: dryer

        ##########################################################
        ## Washing Machine Done - Audio Notification
        ##########################################################

- alias: Laundry - Washing Machine Done Audio Notification
  id: 'laundry_washing_machine_done_audio_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.washer_wash_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'

  actions:
    - action: media_player.play_media
      target:
        entity_id: 
          - media_player.sonos_living_room
          - media_player.sonos_kitchen
          - media_player.sonos_bathroom
          - media_player.sonos_USER1s_office
          - media_player.sonos_USER2s_office
          - media_player.sonos_move
          - media_player.sonos_fitness_room
          - media_player.sonos_craft_room
      data:
        announce: true
        media_content_id: >
          media-source://tts/cloud?message="Washing Machine Has Finished"
        media_content_type: "music"
        extra:
          volume: 45

        ##########################################################
        ## Dryer Done - Audio Notification
        ##########################################################

- alias: Laundry - Dryer Done Audio Notification
  id: 'laundry_dryer_done_audio_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.dryer_dry_completed
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 1

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '20:00:00'

  actions:
    - action: media_player.play_media
      target:
        entity_id: 
          - media_player.sonos_living_room
          - media_player.sonos_kitchen
          - media_player.sonos_bathroom
          - media_player.sonos_USER1s_office
          - media_player.sonos_USER2s_office
          - media_player.sonos_move
          - media_player.sonos_fitness_room
          - media_player.sonos_craft_room
      data:
        announce: true
        media_content_id: >
          media-source://tts/cloud?message="Dryer Has Finished"
        media_content_type: "music"
        extra:
          volume: 45

        ##########################################################
        ## Washer Run Tub Clean Notification
        ##########################################################

- alias: Laundry - Washer Run Tub Clean Notification
  id: 'laundry_washer_run_tub_clean_notification'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.washer_tub_clean
      above: 29

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Time to Run a Tub Clean Cycler on the Washer
        data:
          tag: washer-clean