#################################################################
## Weather Based Automations
#################################################################

        ##########################################################
        ## Turn Globe Blue when Raining
        ##########################################################

- alias: Weather - Turn Globe Blue when Raining
  id: 'weather_turn_globe_blue_when_raining'

  triggers:
    - trigger: state
      entity_id: weather.REDACTED
      to: 'rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - trigger: state
      entity_id: weather.REDACTED
      to: 'lightning-rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.globe
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.globe
      data:
        color_name: blue
        brightness_pct: 100
        transition: 15

        ##########################################################
        ## Reset Globe Color when Not Raining
        ##########################################################

- alias: Weather - Reset Globe Color when Not Raining
  id: 'weather_reset_globe_color_when_not_raining'

  triggers:
    - trigger: state
      entity_id: weather.REDACTED
      from: 'rainy'
    - trigger: state
      entity_id: weather.REDACTED
      from: 'lightning-rainy'

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.globe
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.globe
      data:
        brightness_pct: 65
        color_temp: 366
        transition: 15

        ##########################################################
        ## Set Globe Blue when On and Raining
        ##########################################################

- alias: Weather - Set Globe Blue when On and Raining
  id: 'weather_set_globe_blue_when_on_and_raining'

  triggers:
    - trigger: state
      entity_id: light.globe
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.livingroom_rainbow
      state: 'off'
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'disarmed'
    - condition: or
      conditions:
      - condition: state
        entity_id: weather.REDACTED
        state: 'rainy'
      - condition: state
        entity_id: weather.REDACTED
        state: 'lightning-rainy'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kitchen_sink_water_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bathroom_sink_water_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.upstairs_bathrooom_water_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.utility_sink_water_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.washing_machine_water_sensor
        state: 'off'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.globe
      data:
        color_name: blue
        brightness_pct: 100
        transition: 15

        ##########################################################
        ## Turn USER1's Office Desk Lamp Blue when Raining
        ##########################################################

- alias: Weather - Turn USER1's Office Desk Lamp Blue when Raining
  id: 'weather_turn_USER1_office_desk_lamp_blue_when_raining'

  triggers:
    - trigger: state
      entity_id: weather.REDACTED
      to: 'rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - trigger: state
      entity_id: weather.REDACTED
      to: 'lightning-rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: light.USER1_office_desk_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_office_desk_lamp
      data:
        color_name: blue
        brightness_pct: 25

        ##########################################################
        ## Turn USER1's Office Accent Light Blue when Raining
        ##########################################################

- alias: Weather - Turn USER1's Office Accent Light Blue when Raining
  id: 'weather_turn_USER1_office_accent_light_blue_when_raining'

  triggers:
    - trigger: state
      entity_id: weather.REDACTED
      to: 'rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - trigger: state
      entity_id: weather.REDACTED
      to: 'lightning-rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: light.USER1_office_desk_accent
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'closed'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_office_desk_accent
      data:
        color_name: blue
        brightness_pct: 100
        transition: 15

        ##########################################################
        ## Reset USER1's Office Desk Lamp Color when Not Raining
        ##########################################################

- alias: Weather - Reset USER1's Office Desk Lamp Color when Not Raining
  id: 'weather_reset_USER1_office_desk_lamp_color_when_not_raining'

  triggers:
    - trigger: state
      entity_id: weather.REDACTED
      from: 'rainy'
    - trigger: state
      entity_id: weather.REDACTED
      from: 'lightning-rainy'

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: light.USER1_office_desk_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_office_desk_lamp
      data:
        brightness_pct: 25
        color_temp: 454

        ##########################################################
        ## Reset USER1's Office Accent Light Color when Not Raining
        ##########################################################

- alias: Weather - Reset USER1's Office Accent Light Color when Not Raining
  id: 'weather_reset_USER1_office_accent_light_color_when_not_raining'

  triggers:
    - trigger: state
      entity_id: weather.REDACTED
      from: 'rainy'
    - trigger: state
      entity_id: weather.REDACTED
      from: 'lightning-rainy'

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: light.USER1_office_desk_accent
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_office_desk_accent
      data:
        brightness_pct: 80
        color_temp: 370
        transition: 15

        ##########################################################
        ## Set USER1's Office Desk Lamp Blue when On and Raining
        ##########################################################

- alias: Weather - Set USER1's Office Desk Lamp Blue when On and Raining
  id: 'weather_set_USER1_office_desk_lamp_blue_when_on_and_raining'

  triggers:
    - trigger: state
      entity_id: light.USER1_office_desk_lamp
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.office_rainbow
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: weather.REDACTED
        state: 'rainy'
      - condition: state
        entity_id: weather.REDACTED
        state: 'lightning-rainy'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_office_desk_lamp
      data:
        color_name: blue
        brightness_pct: 25

        ##########################################################
        ## Set USER1's Office Accent Light Blue when On and Raining
        ##########################################################

- alias: Weather - Set USER1's Office Accent Light Blue when On and Raining
  id: 'weather_set_USER1_office_accent_light_blue_when_on_and_raining'

  triggers:
    - trigger: state
      entity_id: light.USER1_office_desk_accent
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.office_rainbow
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: weather.REDACTED
        state: 'rainy'
      - condition: state
        entity_id: weather.REDACTED
        state: 'lightning-rainy'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_office_desk_accent
      data:
        color_name: blue
        brightness_pct: 100
        transition: 15